### ISSUE TITLE
ImportError: cannot import name 'escape' from 'jinja2'

### ISSUE THREAD

**Issue by stuartmac** [bartongroup/slivka-bio#5]
While attempting to start the slivka server within the compbio-services conda environment, I received the following error:

ImportError: cannot import name 'escape' from 'jinja2' (/Users/smacgowan/mambaforge/envs/compbio-services/lib/python3.9/site-packages/jinja2/__init__.py)

## Steps to reproduce
1. Install slivka/compbio-services environment
2. Run slivka start server.

## Cause
I found a [StackOverflow post](https://stackoverflow.com/questions/71718167/importerror-cannot-import-name-escape-from-jinja2) indicating that this issue could arise due to Flask V1.X.X's dependency on the escape module from Jinja, which was dropped in recent Jinja versions.

The issue seems to be resolved by updating Flask to version V2.X.X where it no longer relies on the escape module from Jinja. I updated Flask within my conda environment and managed to progress past this issue, although I haven't fully tested the server.

## Suggested fix
t might be useful to specify in the setup or requirements that Flask V2.X.X is necessary.

**Comment by warownia1** [comment]
Thanks for spotting this. There are some incompatibilities between slivka and Flask 2.x which has been patched in the latest version available on GitHub. I will make sure that conda libraries are updated as well. The patched version with resolved dependency issues is 0.8.1b1.
